[package]
name = "llvm-extra-sys"
version = "0.1.0"
license = "Apache 2.0 / MIT"
edition = "2021"

[dependencies]
libc = "0.2"
llvm-sys = "150.0.3"

[build-dependencies]
cc = "1.0.78"
anyhow = "1.0.68"
